apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: epfkx0mre-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: epfkx0mre-go 
  name: epfkx0mre-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: epfkx0mre-go 
